version: "3.7"

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/app
            - ./docker/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "8111:80"
    db:
        # platform: linux/x86_64
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: development_db
        ports:
            - "33062:3306"
        volumes:
            - dbdata:/var/lib/mysql/

    mailcatcher:
        image: schickling/mailcatcher
        ports:
        - '1080:1080'
        - '1025:1025'

volumes:
    dbdata:
        driver: local
